### ISSUE TITLE
导出来的未翻译文件里有很多[ERROR KEY]

### ISSUE THREAD

**Issue by KangX** [hhhxiao/SoulsModTranslator#3]
![image](https://github.com/hhhxiao/SoulsModTranslator/assets/11532035/63dbc3f3-9e58-4859-beee-5ab93e510e8c)

**Comment by hhhxiao** [comment]
有日志吗，还有具体怎么操作的也描述一下，估计是术语表的问题

**Comment by KangX** [comment]
> 有日志吗，还有具体怎么操作的也描述一下，估计是术语表的问题

就常规的操作，按视频里来的，我刚刚想复现一下把日志发给你看，但是我把原来的日志文件全部删除以后再次操作，又好了，出来的excel文件里又没有那堆error key了

**Comment by hhhxiao** [comment]
行吧，那先关了
